# Generated by Django 3.1.7 on 2021-06-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='quote',
            field=models.TextField(null=True),
        ),
    ]
