# Generated by Django 3.1.7 on 2021-06-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210605_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='seo_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='seo_title',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
